# -*- coding: utf-8 -*-
"""Counting Email in a Database.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rHuVoTwDQ1WCWfDmMghWq-DDlMk5VGbx
"""

!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

downloaded = drive.CreateFile({'id':'1N4g702Gs16wQG9LUemzCufuX-PfsYqYz'}) # replace the id with id of file you want to access
downloaded.GetContentFile('mbox.txt')

# You can use this code as a starting point for your application: http://www.py4e.com/code3/emaildb.py.
# The data file for this application is the same as in previous assignments: http://www.py4e.com/code3/mbox.txt.

import sqlite3
conn = sqlite3.connect('T2.sqlite')
cur = conn.cursor()
cur.execute('DROP TABLE IF EXISTS Counts')
cur.execute('''
CREATE TABLE Counts (org TEXT, count INTEGER)''')
 
fname = input('Enter file name: ')
if (len(fname) < 1): fname = 'mbox.txt'
fh = open(fname)
for line in fh:
    if not line.startswith('From: '): continue
    pieces = line.split()
    email = pieces[1].split('@')
    p = email[1]
    cur.execute('SELECT count FROM Counts WHERE org = ? ', (p,))
    row = cur.fetchone()
    if row is None:
        cur.execute('''INSERT INTO Counts (org, count)
                VALUES (?, 1)''', (p,))
    else:
        cur.execute('UPDATE Counts SET count = count + 1 WHERE org = ?',
                    (p,))
    conn.commit()
 
sqlstr = 'SELECT org, count FROM Counts ORDER BY count DESC'
for row in cur.execute(sqlstr):
    print(str(row[0]), row[1])
cur.close()

